apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  # annotations:
  #   service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: sniperadmin/nuxt3-poc
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "1500Gi"
        ports:
        - containerPort: 80
