apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  argocd-nuxt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sniperadmin/poc-universal-nuxt.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
